Raise minimum tested compiler to 1.65
Required by the transitive dependency on regex-automata, through bindgen:

    error: package `regex-automata v0.4.1` cannot be built because it
    requires rustc 1.65 or newer, while the currently active rustc
    version is 1.63.0